version: '3.8'

services:
  vanna-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vanna-flask-app
    ports:
      - "80:5000"
      - "443:5000"
    environment:
      # These should be provided via .env file or environment variables
      - VANNA_MODEL=${VANNA_MODEL}
      - VANNA_API_KEY=${VANNA_API_KEY}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USERNAME=${SNOWFLAKE_USERNAME}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - FLASK_ENV=production
    volumes:
      # Mount static files if you need to persist them
      - ./static:/app/static:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vanna-network


networks:
  vanna-network:
    driver: bridge

# Optional: Add volumes for persistent data if needed
volumes:
  static_files:
    driver: local