# Docker Compose file for running the application with production settings
version: '3.8'

services:
  vanna-flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vanna-flask-app
    ports:
      - "5000:5000"
    environment:
      # Required environment variables - must be updated with actual values
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # Vanna.AI variables - must add actual values
      - VANNA_MODEL=${VANNA_MODEL}
      - VANNA_API_KEY=${VANNA_API_KEY}
      # Snowflake variables - must add actual values
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USERNAME=${SNOWFLAKE_USERNAME}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
    volumes:
      # Mount .env file if it exists (optional)
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vanna-network

networks:
  vanna-network:
    driver: bridge